"""WOGHAW E-02 — deterministic materializer: WO Workflow Definition + routing profile -> provider-specific gh-aw
workflow sources (lab instrument, NOT the WO product). The WD is the single definition; each generated .md is a
provider-specific materialization that only differs in the engine block and the selected role.
Usage: wo_materialize.py <wd.json> <routing.json> <out_dir>"""
import hashlib, json, sys

wd_path, rt_path, out = sys.argv[1:4]
wd_raw, rt_raw = open(wd_path, "rb").read(), open(rt_path, "rb").read()
wd, rt = json.loads(wd_raw), json.loads(rt_raw)
wd_sha, rt_sha = hashlib.sha256(wd_raw).hexdigest(), hashlib.sha256(rt_raw).hexdigest()
env = wd["envelope"]
for role, engine in sorted(rt["routes"].items()):
    r = wd["roles"][role]
    md = f"""---
name: WOGHAW E-02 {role} ({engine})
on:
  workflow_dispatch:
    inputs:
      wo_operation_id:
        description: WO operation_id
        required: true
        type: string
      wo_attempt_id:
        description: WO attempt_id
        required: true
        type: string
  push:
    branches: [woghaw-phase3-targets]
if: github.event_name == 'workflow_dispatch'
run-name: "WOGHAW E-02 ${{{{ inputs.wo_operation_id }}}} ${{{{ inputs.wo_attempt_id }}}} {role} {engine}"
permissions:
  contents: read
engine:
  id: {engine}
  max-turns: {env['max_turns']}
  harness:
    max-retries: {env['harness_max_retries']}
  env:
    GH_AW_HARNESS_STARTUP_RETRIES: "{env['startup_retries']}"
max-ai-credits: {env['max_ai_credits']}
timeout-minutes: {env['timeout_minutes']}
tools:
  bash: false
  cli-proxy: false
  edit: false
  github: false
safe-outputs:
  github-token: ${{{{ secrets.GITHUB_TOKEN }}}}
  report-failure-as-issue: false
  report-failed-jobs: false
  noop:
    report-as-issue: false
  missing-tool:
    create-issue: false
  missing-data:
    create-issue: false
  report-incomplete:
    create-issue: false
  threat-detection: false
  jobs:
    wo-result:
      description: "Report the single result value of this WO task. It performs no action other than recording the value."
      runs-on: ubuntu-latest
      permissions: {{}}
      output: "recorded"
      inputs:
        value:
          description: "The result value"
          required: true
          type: string
      steps:
        - name: WO result (no GitHub effect)
          run: |
            v=$(jq -c '[.items[] | select(.type == "wo_result") | .value]' "$GH_AW_AGENT_OUTPUT" 2>/dev/null || echo '"unreadable"')
            echo "::notice title=WO_E02_RESULT::{{\\"wd_id\\":\\"{wd['wd_id']}\\",\\"wd_sha256\\":\\"{wd_sha}\\",\\"role\\":\\"{role}\\",\\"engine\\":\\"{engine}\\",\\"values\\":$v}}"
jobs:
  wo_evidence:
    needs: [agent]
    if: always() && needs.agent.result != 'skipped'
    runs-on: ubuntu-latest
    permissions: {{}}
    steps:
      - name: WO E-02 agent job evidence
        env:
          WO_AGENT_RESULT: ${{{{ needs.agent.result }}}}
          WO_AGENT_AIC: ${{{{ needs.agent.outputs.aic }}}}
          WO_AGENT_MODEL: ${{{{ needs.agent.outputs.model }}}}
          WO_ATTEMPT_ID: ${{{{ inputs.wo_attempt_id }}}}
        run: echo "::notice title=WO_E02_AGENT_JOB::{{\\"attempt_id\\":\\"${{WO_ATTEMPT_ID}}\\",\\"role\\":\\"{role}\\",\\"engine\\":\\"{engine}\\",\\"agent_result\\":\\"${{WO_AGENT_RESULT}}\\",\\"aic\\":\\"${{WO_AGENT_AIC}}\\",\\"model\\":\\"${{WO_AGENT_MODEL}}\\"}}"
---

<!-- GENERATED by .wo/wo_materialize.py from {wd['wd_id']} v{wd['version']} (sha256 {wd_sha}) and {rt['routing_id']} (sha256 {rt_sha}); role={role}; engine={engine}. Do not edit. -->

# {wd['wd_id']} — role `{role}`

This is a controlled validation run. You have no shell, no file editing and no GitHub tools; do not try to use any.

Input text: `{wd['input']['text']}`

Rule: {wd['input']['rule']}.

Task: {r['task']}

Result: {r['result']}.

Call the safe-output tool `wo_result` exactly once with `value` set to the result, then stop. Do not call any other tool.
"""
    open(f"{out}/woghaw-e02-{role}-{engine}.md", "w").write(md)
    print(f"{role} -> {engine}: woghaw-e02-{role}-{engine}.md (wd {wd_sha[:12]}, routing {rt_sha[:12]})")
